<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>JohnOtt.Utilities</PackageId>
    <Version>1.0.0</Version>
    <Authors>John Ott</Authors>
    <Description>Shared utility library for my .NET applications.</Description>
    <RepositoryUrl>https://github.com/JohnOtt1962/Utilities</RepositoryUrl>
    <PackageReadmeFile>docs\README.md</PackageReadmeFile>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>
  
  <ItemGroup>
    <None Include="docs\README.md" Pack="true" PackagePath="docs\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MailKit" Version="4.17.0" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.10" />
    <PackageReference Include="MimeKit" Version="4.17.0" />
  </ItemGroup>

</Project>
